apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        app: app-1-system-6tdks4
    name: app-1-system-6tdks4-deploy
    namespace: default
spec:
    replicas: 1
    selector:
        matchLabels:
            app: app-1-system-6tdks4
    template:
        metadata:
            labels:
                app: app-1-system-6tdks4
        spec:
            containers:
                - image: nginx:1.14.2
                  imagePullPolicy: IfNotPresent
                  name: app-1-system-6tdks4
                  resources:
                    limits:
                        cpu: 1
                        memory: 2000Mi
                    requests:
                        cpu: 0.1
                        memory: 100Mi
            restartPolicy: Always
