apiVersion: v1
kind: Service
metadata:
  name: app-1-system-zqbfjm-service
  namespace: default
  labels:
    service: app-1-system-zqbfjm
spec:
  selector:
    app: app-1-system-zqbfjm
  type: NodePort
  ports:
    - name: app-1-system-zqbfjm-port
      protocol: TCP
      port: 80
      targetPort: 80
